blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
]

blogs/urls.py
"""Defines URL patterns for blogs"""

from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    # Home page
    path('', views.index, name = 'index'),
    # Page that shows all blog posts
    path('posts/', views.posts, name='posts'),
    # Detail page for a single post
    path('posts/<int:post_id>/', views.post, name='post'),
    # Page for adding a new post
    path('new_post/', views.new_post, name='new_post'),
    # Page for adding a new comment
    path('new_comment/<int:post_id>/', views.new_comment, name='new_comment'),
    # Page for editing a post
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    # Page of users the user is following
    path('following/', views.following, name='following'),
    # Home page for user
    path('<str:userpage_id>/', views.user_page, name='user_page'),
    # Page for follow count
    path('followers_count', views.followers_count, name='followers_count'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

# Set app name so Django can distinguish these user urls from other app urls
app_name = 'users'
urlpatterns = [
    # Include default auth urls, this statement gives prewritten Django user URLs
    # Things like login, logout, etc. will be included with default view functions
    path('', include('django.contrib.auth.urls')),
    # Regristration page.
    path('register/', views.register, name='register'),
]

blogs/models.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    """A Blog Post with a title, text, and date added"""
    title = models.CharField(max_length=200)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Blog Posts'

    def __str__(self):
        """Return a string representation of the model"""
        if len(self.title) > 50:
            return f"{self.title[:50]}..."
        else:
            return f"{self.title}"

class Comment(models.Model):
    """Comment for a particular Blog Post"""
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        """Return a string representation of the model"""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

class FollowersCount(models.Model):
    follower = models.CharField(max_length=1000)
    user = models.CharField(max_length=1000)

    def __str__(self):
        return self.user

blogs/forms.py
from django import forms

from .models import BlogPost, Comment

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

blogs/views.py
from contextlib import ContextDecorator
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import BlogPost, Comment, User, FollowersCount
from .forms import BlogPostForm, CommentForm

# Create your views here.
def index(request):
    """The home page for Blog"""
    return render(request, 'blogs/index.html')

def posts(request):
    """Show all posts"""
    posts = BlogPost.objects.order_by('-date_added')
    context = {'posts' : posts}
    return render(request, 'blogs/posts.html', context)

def post(request, post_id):
    """Show a single post and it's text/comments"""
    post = BlogPost.objects.get(id=post_id)
    
    comments = post.comment_set.order_by('-date_added')
    context = {'post': post, 'comments': comments}
    return render(request, 'blogs/post.html', context)

@login_required
def new_post(request):
    """Add a new post"""
    
    if request.method != 'POST':
        # No data submitted, create a blank form
        form = BlogPostForm()
    else:
        # POST submitted, process data
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:posts')
    
    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)

@login_required
def new_comment(request, post_id):
    """Add a new comment"""
    post = BlogPost.objects.get(id=post_id)

    if request.method != 'POST':
        # No data submitted, create a blank form
        form = CommentForm()
    else:
        # POST submitted, process data
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.owner = request.user
            new_comment.post = post
            new_comment.save()
            return redirect('blogs:post', post_id=post_id)
    
    # Display a blank or invalid form
    context = {'post': post, 'form': form}
    return render(request, 'blogs/new_comment.html', context)

@login_required
def edit_post(request, post_id):
    """Edit an existing post"""
    post = BlogPost.objects.get(id=post_id)

    check_topic_owner(request, post)

    if request.method != 'POST':
        # Initial request, pre-fill form with current entry
        form = BlogPostForm(instance=post)
    else:
        # POST data submitted, process data
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:post', post_id=post.id)
    
    context = {'post': post, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

def user_page(request, userpage_id):
    """Displaying a user's personal page"""

    # Get the username of the page's owner
    userpage = User.objects.get(username=userpage_id)
    logged_in = request.user.username

    # Get a list the number of followers and following the user has
    user_followers = len(FollowersCount.objects.filter(user=userpage.username))
    user_following = len(FollowersCount.objects.filter(follower=userpage.username))

    # Make a list of users that are following the page's user
    user_followers_list = FollowersCount.objects.filter(user=userpage.username)
    user_followers_true_list = []
    for i in user_followers_list:
        user_followers_list = i.follower
        user_followers_true_list.append(user_followers_list)

    # Make a list of users that this page's user follows
    user_following_list = FollowersCount.objects.filter(follower=userpage.username)
    user_following_true_list = []
    for i in user_following_list:
        user_following_list = i.user
        user_following_true_list.append(user_following_list)

    # If the logged in user is in the following list let them unfollow, let them follow otherwise
    if logged_in in user_followers_true_list:
        follow_button_value = 'unfollow'
    else:
        follow_button_value = 'follow'

    # Get the posts this user has made
    posts = BlogPost.objects.filter(owner=User.objects.get(username=userpage_id)).order_by('-date_added')

    context = {
        'userpage': userpage, 'posts': posts,
        'user_followers': user_followers,
        'user_following': user_following,
        'follow_button_value': follow_button_value,
        'user_followers_list': user_followers_true_list,
        'user_following_list': user_following_true_list,
        }
    return render(request, 'blogs/user_page.html', context)

@login_required
def followers_count(request):
    """Let user follow or unfollow"""
    if request.method == 'POST':
        # Getting these values from the buttons named ['name']
        value = request.POST['value']
        user = request.POST['user']
        follower = request.POST['follower']
        if value == 'follow':
            follower_cnt = FollowersCount.objects.create(follower=follower, user=user)
            follower_cnt.save()
        else:
            follower_cnt = FollowersCount.objects.get(follower=follower, user=user)
            follower_cnt.delete()

        return redirect('/'+user)

@login_required
def following(request):
    """Brings user to page of posts from users they follow"""
    logged_in = request.user.username

    user_following_list = FollowersCount.objects.filter(follower=logged_in)

    # Make a list of the usernames
    user_following_true_list = []
    for i in user_following_list:
        user_following_list = i.user
        user_following_true_list.append(user_following_list)

    users = User.objects.filter(username__in=user_following_true_list)
    posts = BlogPost.objects.filter(owner__in=users).order_by('-date_added')

    context = {'posts': posts}
    
    return render(request, 'blogs/following.html', context)



# Make sure user associated with topic is the current user
def check_topic_owner(request, post):
     if post.owner != request.user:
        raise Http404

blogs/templates/blogs/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'blogs:index' %}">My Blog</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blogs:user_page' user.username %}">My Page</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'blogs:posts' %}">Posts</a>
                </li>
            </ul>

            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'blogs:following' %}">Following</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <!-- used a span for a non-clickable item -->
                    <span class="nav-link active">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
                {% endif %}
              </li>
            </ul>
          </div>
        </div>
    </nav>

    <main role="main" class="container">
        <!-- div used for the header of a page. "pb-2" adds padding, "mb-2" adds margin, 
        "border-bottom" adds a border to the bottom of the div -->
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <!-- div for the content different to each page -->
        <div>
            {% block content %}{% endblock content %}
        </div>

    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}
{% load bootstrap5 %}

{% block page_header %}
    <h2 class="mt-2"><a href="{% url 'blogs:post' post.id %}">{{ post }}</a></h2>
{% endblock page_header %}

{% block content %}

    <h4>Edit post:</h4>

    <form action="{% url 'blogs:edit_post' post.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-outline-primary">Save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

blogs/templates/blogs/following.html
{% extends "blogs/base.html" %}

{% block page_header %}
    <h2 class="mt-2">Following</h2>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for post in posts %}

            <!-- Show the lastest 100 posts -->
            {% if forloop.counter0 <= 30 %}
            <li class="fs-5">
                <a href="{% url 'blogs:post' post.id %}">{{ post }}</a>
                - {{ post.date_added}} - by: 
                <a href="{% url 'blogs:user_page' post.owner %}">{{post.owner}}</a>
            </li>
            {% endif %}

        {% empty %}
        <h4><li>You are not following anyone yet.</li></h4>
        {% endfor %}
    </ul>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
<!-- "extends" tells this child template what parent to inherit from and is on the 1st line
base.html is a part of learning_logs so we include that in the path -->

<!-- Fill in the block page_header set up by parent template -->
{% block page_header %}
    <!-- div that uses the "jumbotron" class that is typically used to into home pages-->
    <div class="mt-4 p-5 bg-light rounded">
        <!-- Header with a "display-3" class that makes it taller and thinner -->
        <h1 class="display-3">My Blog: Get Started Writing.</h1>

        <p class="lead">
            Create your own blog page to share your stories with others. Follow friends or engrossing
            authors to see the things they have to share. My Blog is a long-form social media
            where you can follow others and hear their thoughts in a longer, well-thought out manner.
        </p>

        {% if user.is_authenticated %}
            <a class="btn btn-lg btn-primary" href="{% url 'blogs:user_page' user.username %}" role="button">
            My Page &raquo;</a>
        
        {% else %}
            <!-- Link with class selectors that make it a large button that stands out 
            "&raquo;" is an HTML entity that looks like >> -->
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">
            Register &raquo;</a>
        {% endif %}

    </div>

{% endblock page_header %}

{% block content %}
    <div class="m-4">
        <h2>How to get started</h2>
        <p>Make your own account to write blog posts on. On "My Page" you can share the link
            to your page with friends so they can follow you and keep up with your posts. On the "Posts"
            page you can see the most recent 100 posts. On "Following" you can see the most recent 30
            posts of the people you are following on your account.</p>
    </div>
{% endblock content %}

blogs/templates/blogs/new_comment.html
{% extends "blogs/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
    <h2 class="mt-2"><a href="{% url 'blogs:post' post.id %}">{{ post }}</a></h2>
{% endblock page_header %}

{% block content %}

    <p>Add a new comment</p>
    <form action="{% url 'blogs:new_comment' post.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button name="submit" class="btn btn-outline-primary">Add comment</button>
    </form>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap5 %}

{% block page_header %}
    <h2 class="mt-2">Add a new post:</h2>
{% endblock page_header %}

{% block content %}

    <form action="{% url 'blogs:new_post' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button name="submit" class="btn btn-outline-primary">Add post</button>
    </form>

{% endblock content %}

blogs/templates/blogs/post.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <h2 class="mt-2">{{ post|title }} by <a href="{% url 'blogs:user_page' post.owner %}">{{ post.owner }}</a></h2>

    <p>{{ post.date_added|date:'M d, Y H:i' }}</p>

    {% if user.id == post.owner.id  %}
    <p>
        <a href="{% url 'blogs:edit_post' post.id %}">Edit post</a>
    </p>
    {% endif %}

    <p class="fs-5">{{ post.text|linebreaks }}</p>
    
{% endblock page_header %}

{% block content %}

    <h4 class="mt-4">Comments:</h4>

    <p>
        <a href="{% url 'blogs:new_comment' post.id %}">Add new comment</a>
    </p>

    {% for comment in comments %}
        <!-- For each entry make a div that looks like a "card" -->
        <div class="card mb-3">

            <!-- "card-header" class makes it so this will be the top section of the card -->
            <h6 class="card-header">
                <!-- In Djagno templates the | represents a template filer, which modifies the 
                value in the tamplate variable and how it is displayed -->
                <a href="{% url 'blogs:user_page' comment.owner %}">{{ comment.owner }}</a>
                - {{ comment.date_added|date:'M d, Y H:i' }}
                <!-- <small> makes this link comparaively smaller -->
            </h6>

            <!-- "card-body" makes it the main content of the card -->
            <div class="card-body">
                <!-- |linebreaks will make it so the text will be formatted and have linbreak in
                a way that fits the browser-->
                {{ comment.text|linebreaks }}
            </div>
        </div>

    {% empty %}
        <p>There are no comment for this topic yet.</p>
    {% endfor %}

{% endblock content %}

blogs/templates/blogs/posts.html
{% extends "blogs/base.html" %}


{% block page_header %}
    <h2 class="mt-2">Posts</h2>
{% endblock page_header %}

{% block content %}

    <a href="{% url 'blogs:new_post' %}" class="fs-5">Add a new post</a>

    <ul>
        {% for post in posts %}

            <!-- Show the lastest 100 posts -->
            {% if forloop.counter0 <= 99 %}
            <li class="fs-5">
                <a href="{% url 'blogs:post' post.id %}">{{ post|title }}</a>
                : {{ post.date_added}} - by: 
                <a href="{% url 'blogs:user_page' post.owner %}">{{post.owner}}</a>
            </li>
            {% endif %}

        {% empty %}
        <li><h4>No posts have been added yet.</li></h4>
        {% endfor %}
    </ul>


{% endblock content %}

blogs/templates/blogs/user_page.html
{% extends "blogs/base.html" %}

{% block page_header %}
    <h2 class="mt-2">{{ userpage.username|title }}'s Blog</h2>


    <!-- Modal button -->
    <button type="button" class="btn btn-sm" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        {{ user_followers }} followers
    </button>

    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Followers</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% for follow_user in user_followers_list %}
                    <p><a href="{% url 'blogs:user_page' follow_user %}">{{ follow_user }}</a></p>
                {% endfor %}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

    <button type="button" class="btn btn-sm" data-bs-toggle="modal" data-bs-target="#staticBackdrop2">
        {{ user_following }} following
    </button>

    <div class="modal fade" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Following</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                {% for follow_user in user_following_list %}
                    <a href="{% url 'blogs:user_page' follow_user %}">{{ follow_user }}</a>
                {% endfor %}
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>


    <!-- <p class="profile-stats text-secondary">{{ user_followers }} followers {{ user_following }} following</p> -->

    {% if user.username != userpage.username %}
        <form action="/followers_count" method="POST">
            {% csrf_token %}
            <input type="hidden" name="user" value="{{userpage.username}}" readonly/>
            <input type="hidden" name="follower" value="{{user}}" readonly/>

            {% if follow_button_value == 'follow' %}
            <input type="hidden" name="value" value="follow" readonly/>
            <button type="submit" class="btn btn-sm btn-outline-primary">
                Follow
            </button>
            {% else %}
            <input type="hidden" name="value" value="unfollow" readonly/>
            <button type="submit" class="btn btn-sm btn-primary">
                Unfollow
            </button>
            {% endif %}
        </form>
    {% endif %}
{% endblock page_header %}

{% block content %}
    

    

    {% if userpage.username == user.username %}
        <a href="{% url 'blogs:new_post' %}" class="fs-5">Add a new post</a>
    {% endif %}

    <ul>
        {% for post in posts %}
            <li>
                <a href="{% url 'blogs:post' post.id %}" class="fs-5">{{ post }}</a> - {{ post.date_added }}
            </li>
        {% empty %}
        <li>No posts have been added yet.</li>
        {% endfor %}
    </ul>


{% endblock content %}